# Generated by Django 4.0.6 on 2022-07-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classView', '0002_data_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[('', '---Select---'), ('1', 'Done'), ('2', 'Pending')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='classView.data')),
            ],
        ),
    ]
